# Generated by Django 3.1.5 on 2021-03-24 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=10)),
                ('d_local', models.CharField(max_length=50)),
                ('d_department', models.CharField(max_length=50)),
                ('d_hospital', models.CharField(max_length=50)),
                ('d_phone', models.CharField(max_length=30)),
                ('d_title', models.CharField(max_length=50)),
                ('d_experience', models.CharField(max_length=150)),
                ('d_education', models.CharField(max_length=150)),
                ('d_skills', models.CharField(max_length=150)),
                ('d_mooto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=10)),
                ('u_age', models.CharField(max_length=10)),
                ('u_gender', models.CharField(max_length=10)),
                ('d_name', models.CharField(max_length=50)),
                ('i_description', models.CharField(max_length=100)),
                ('u_account', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='User.user', to_field='u_account')),
            ],
        ),
    ]
