# Generated by Django 3.1.5 on 2021-03-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0002_auto_20210326_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='u_account',
            field=models.CharField(max_length=10),
        ),
    ]
