# Generated by Django 3.1.5 on 2021-03-27 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0003_auto_20210326_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_department', models.CharField(max_length=50)),
                ('d_id', models.IntegerField(max_length=5)),
                ('info_id', models.IntegerField(max_length=5)),
                ('is_working', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('opentime', models.DateTimeField()),
                ('is_subsequent_visit', models.BooleanField(default=False)),
                ('subsequent_visit_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('done_time', models.DateTimeField()),
            ],
        ),
    ]
