# Generated by Django 3.1.5 on 2021-03-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0004_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='d_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='info_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='subsequent_visit_time',
            field=models.DateTimeField(),
        ),
    ]
