# Generated by Django 3.1.5 on 2021-03-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0005_auto_20210327_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
    ]
