# Generated by Django 3.1.5 on 2021-03-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0006_doctorinfo_is_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='done_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='opentime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='subsequent_visit_time',
            field=models.DateTimeField(null=True),
        ),
    ]
