# Generated by Django 3.1.5 on 2021-03-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0007_auto_20210327_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='u_id',
            field=models.IntegerField(null=True),
        ),
    ]
