# Generated by Django 3.1.5 on 2021-03-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0008_appointment_u_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='ill',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
