# Generated by Django 3.1.5 on 2021-03-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.IntegerField()),
                ('master', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=150)),
                ('flag', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_doctor_id', models.IntegerField()),
                ('e_department_id', models.IntegerField()),
                ('e_hospital_id', models.IntegerField()),
                ('e_user_id', models.IntegerField()),
                ('e_appointment', models.IntegerField()),
                ('e_state', models.IntegerField()),
            ],
        ),
    ]
