# Generated by Django 3.1.5 on 2021-03-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_account', models.CharField(max_length=20, unique=True)),
                ('d_password', models.CharField(max_length=20)),
                ('d_sex', models.CharField(max_length=20)),
                ('d_name', models.CharField(max_length=20)),
                ('d_phone', models.CharField(max_length=11, unique=True)),
                ('d_history', models.CharField(max_length=100)),
                ('d_age', models.IntegerField()),
                ('d_department', models.IntegerField()),
                ('d_hospital', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_account', models.CharField(max_length=20, unique=True)),
                ('u_password', models.CharField(max_length=20)),
                ('u_email', models.CharField(max_length=20)),
            ],
        ),
    ]
