# Generated by Django 3.0.6 on 2020-11-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_account', models.CharField(max_length=20, unique=True)),
                ('u_password', models.CharField(max_length=20)),
            ],
        ),
    ]
